package gui;

import java.io.File;
import javax.swing.filechooser.FileFilter;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Alexander Álvarez Marques
 * @date 2020-09-10
 * @version 0.1
 */
public class Principal extends javax.swing.JFrame {

    // Variables
    JFileChooser fileChooser = new JFileChooser();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBottonPanel = new javax.swing.JPanel();
        applyFilterButton = new javax.swing.JButton();
        panelImageNoFilter = new tools.BackgroundImage();
        authorsPanel = new javax.swing.JPanel();
        copyright = new javax.swing.JLabel();
        authors = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        fileOpen = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        documentation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonBottonPanel.setVisible(false);

        applyFilterButton.setText("Apply filter");

        javax.swing.GroupLayout buttonBottonPanelLayout = new javax.swing.GroupLayout(buttonBottonPanel);
        buttonBottonPanel.setLayout(buttonBottonPanelLayout);
        buttonBottonPanelLayout.setHorizontalGroup(
            buttonBottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonBottonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(applyFilterButton))
        );
        buttonBottonPanelLayout.setVerticalGroup(
            buttonBottonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonBottonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(applyFilterButton))
        );

        javax.swing.GroupLayout panelImageNoFilterLayout = new javax.swing.GroupLayout(panelImageNoFilter);
        panelImageNoFilter.setLayout(panelImageNoFilterLayout);
        panelImageNoFilterLayout.setHorizontalGroup(
            panelImageNoFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        panelImageNoFilterLayout.setVerticalGroup(
            panelImageNoFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        copyright.setText("Copyright:");

        authors.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        authors.setForeground(new java.awt.Color(0, 0, 0));
        authors.setText("Viviana Magali Benitez Sosa & Alexander Álvarez Marques");

        javax.swing.GroupLayout authorsPanelLayout = new javax.swing.GroupLayout(authorsPanel);
        authorsPanel.setLayout(authorsPanelLayout);
        authorsPanelLayout.setHorizontalGroup(
            authorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorsPanelLayout.createSequentialGroup()
                .addComponent(copyright)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        authorsPanelLayout.setVerticalGroup(
            authorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authorsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(authorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyright)
                    .addComponent(authors))
                .addContainerGap())
        );

        file.setMnemonic('f');
        file.setText("File");

        New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        New.setText("New");
        file.add(New);

        fileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        fileOpen.setText("Open");
        fileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenActionPerformed(evt);
            }
        });
        file.add(fileOpen);

        menu.add(file);

        help.setMnemonic('h');
        help.setText("Help");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        about.setMnemonic('a');
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        help.add(about);

        documentation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        documentation.setMnemonic('d');
        documentation.setText("Documentation");
        documentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentationActionPerformed(evt);
            }
        });
        help.add(documentation);

        menu.add(help);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImageNoFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBottonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImageNoFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBottonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenActionPerformed
        
        FileFilter imageFilter =
                new FileNameExtensionFilter("Image files (BMP, JPG, JPEG, WBMP, PNG, GIF)",
                ImageIO.getReaderFileSuffixes());
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int choose = fileChooser.showOpenDialog(menu);
        
        if (choose == JFileChooser.APPROVE_OPTION) {
            
            File selectedFile = fileChooser.getSelectedFile();
            panelImageNoFilter.setImage(selectedFile);
            
            if (panelImageNoFilter.isImageLoaded()) buttonBottonPanel.setVisible(true);
        }
        if (choose == JFileChooser.CANCEL_OPTION) {
            System.out.println("Ahora me cago en tu abuela.");
        }
    }//GEN-LAST:event_fileOpenActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        
        String information = ""
                + "<html>"
                + "<h1>About</h1>"
                + "<p>Date version: 2020-09-10</p>"
                + "<p>Version: 0.1</p>"
                + "<p><b>Viviana Magali Benitez Sosa & Alexander Álvarez Marques</b></p>"
                + "</html>";
        
        JOptionPane.showMessageDialog(this, information, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutActionPerformed

    private void documentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentationActionPerformed
        
        String information = ""
                + "<html>"
                + "<h1>Guide</h1>"
                
                + "<h2>Description</h2>"
                + "<p style=\" text-align: justify;\">"
                + "This program apply a black and white filter to selected image.<br>"
                + "The image result is totally design on black and white colors."
                + "</p>"
                
                + "<h2>How it works</h2>"
                + "<ol>"
                + " <li>Select an image: click on \"File\" menu. Then select \"Open\".</li>"
                + " <li>After select an image, at botton right corner will appear a button (\"Apply filter\")."
                + " To apply the filter click on it</li>"
                + " <li></li>"
                + "</ol>"
                
                + ""
                
                + "</html>";
        
        JOptionPane.showMessageDialog(this, information, "Help", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_documentationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem about;
    private javax.swing.JButton applyFilterButton;
    private javax.swing.JLabel authors;
    private javax.swing.JPanel authorsPanel;
    private javax.swing.JPanel buttonBottonPanel;
    private javax.swing.JLabel copyright;
    private javax.swing.JMenuItem documentation;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem fileOpen;
    private javax.swing.JMenu help;
    private javax.swing.JMenuBar menu;
    private tools.BackgroundImage panelImageNoFilter;
    // End of variables declaration//GEN-END:variables
}
